# Generated by Django 4.1.5 on 2023-01-27 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0003_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighborhood',
            old_name='state',
            new_name='city',
        ),
    ]
